PUT http://localhost:8080/api/v1/people/130
Content-Type: application/json

{
  "id": 130,
  "firstName": "Rodrigo",
  "lastName": "Mercules 2",
  "cpf": "588.470.900-59",
  "birthDate": "11-11-2019",
  "phones": [
    {
      "id": 129,
      "type": "MOBILE",
      "number": "(21)99999999"
    }
  ]
}