PUT http://localhost:8080/api/v1/people/34
Content-Type: application/json

{
    "id": 34,
    "firstName": "David",
    "lastName": "Rufino 2",
    "cpf": "657.396.090-46",
    "birthDate": null,
    "phones": [
      {
        "id": 33,
        "type": "MOBILE",
        "number": "(021)9999-9999"
      }
    ]
  }